language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "ktagg-github"
    token:
      secure: "443e6e0dbdc859c095694c3e91e9609fea571425"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'